#
# This file contains configuration flags for the site
#

name: Eric Kleinschmidt

description: On the Data Science Journey

avatar: https://avatars1.githubusercontent.com/u/26975059?v=4

# Include icon in the footer for each
footer-links:
  email: ericwk@comcast.net
  github: ericwk
  linkedin: ewkleinschmidt

url: https://ericwk.github.io
baseurl: ""

permalink: /:title/

version: v3.8.5

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # pygments syntax highlighting css
    css_class: 'highlight'
    
sass:
  style: :expanded

gems:
  - jekyll-sitemap # Create a sitemap
  - jekyll-feed # Create an Atom feed
  
# Exclude these files from the site
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- CNAME
